spring:
  datasource:
    # H2 Database Settings
    url: jdbc:h2:mem:chequedb
    driverClassName: org.h2.Driver
    username: oveis
    password: removeIt
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    # Show H2 Console
    console:
      enabled: true
      path: /h2 #

server:
  # Server Port (Optional)
  port: 8544

# External SAYAD Service (Mock client)
sayad:
  register:
    url: http://localhost:8081/sayad/register
  present:
    url: http://localhost:8081/sayad/present